name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy app to EC2
      run: |
        ssh -i ~/.ssh/your-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

          sudo docker stop airline-fe || true
          sudo docker rm airline-fe || true

          # Pull latest image
          sudo docker pull ghcr.io/${{ github.repository_owner }}/airline-fe:latest

          sudo docker run -d -p 3001:3001 -e NUXT_PUBLIC_API=https://airline-api.kokai.xyz --name airline-fe ghcr.io/${{ github.repository_owner }}/airline-fe:latest
        EOF
